<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="Mecanum_Wheel" params="PREFIX WIDTH DIAMETER MECANUM_WHEEL_MAX_JOINT_VEL
    MECANUM_WHEEL_MAX_EFFORT FR_BA LE_RI BASE_LENGHT
    BASE_WIDTH BASE_HEIGHT MECANUM_WHEEL_WIDTH BASE_LINK WHEEL_MASS">

    <!-- ********************************************************  -->
    <!-- ****************** MACROS ******************************  -->
    <!-- ********************************************************  -->

    <!-- ******************* INERTIAL MACROS  *******************  -->

    <xacro:include filename="$(find omni_featter_description)/urdf/basic_macros/inertial_macros.urdf.xacro" />

    <!-- ********************************************************  -->
    <!-- *************** MECANUM WHEEL DEFINITION ***************  -->
    <!-- ********************************************************  -->

    <link name="${PREFIX}">

      <visual>
        <geometry>
          <cylinder radius="${DIAMETER/2}" length="${WIDTH}" />
        </geometry>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${DIAMETER/2}" length="${WIDTH}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${WHEEL_MASS}" />
        <xacro:cylinder_inertia m="${MECANUM_WHEEL_MASS}" h="${MECANUM_WHEEL_WIDTH}" r="${DIAMETER/2}"/>
      </inertial>
    </link>

    <joint name="base_to_${PREFIX}_joint" type="continuous">
      <parent link="${BASE_LINK}" />
      <child link="${PREFIX}" />
      <origin xyz="${FR_BA*BASE_LENGHT/2} ${LE_RI*(BASE_WIDTH/2+MECANUM_WHEEL_WIDTH/2)} -${BASE_HEIGHT/2}" rpy="${LE_RI*pi/2} 0 0" />
      <limit effort="${MECANUM_WHEEL_MAX_EFFORT}" velocity="${MECANUM_WHEEL_MAX_JOINT_VEL}" />
      <axis xyz="0 0 1" />
    </joint>


  </xacro:macro>
</robot>